services:
 
  api:
    build:
      context: .  
      dockerfile: ./Dockerfile  
    ports:
      - "1000:1000"
    environment:
      ENVIRONMENT: production
      DATABASE_URL: postgres://postgres:1020@db:5432/Ejemplo?sslmode=disable
    depends_on:
      - db
    networks:
      - red
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1020
      POSTGRES_DB: Ejemplo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - red
    restart: always

volumes:
  pgdata:

networks:
  red:
    driver: bridge